/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_tugas1;

import java.awt.HeadlessException;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DYNABOOK - Chintia Liu Wintin 2109106008
 */
public class FormPendataan extends javax.swing.JFrame {
    
    DefaultTableModel model;
    
    /**
     * Creates new form FormPendataan
     */
    public FormPendataan() {
        initComponents();
        
        cmbKategori.setSelectedIndex(-1);
        txtKode.requestFocus();
        
        String []judul = {"Kode", "Nama", "Brand", "Kategori", "Footwear", "Ukuran", "Gender", "Warna", "Harga"};
        model = new DefaultTableModel(judul,0);
        tbHasil.setModel(model);
        
        tampilData();
        
        tbHasil.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int selectedRow = tbHasil.getSelectedRow();
                if(selectedRow != -1) {
                    String kode = model.getValueAt(selectedRow, 0).toString();
                    String nama = model.getValueAt(selectedRow, 1).toString();
                    String brand = model.getValueAt(selectedRow, 2).toString();
                    String kategori = model.getValueAt(selectedRow, 3).toString();
                    String footwear = model.getValueAt(selectedRow, 4).toString();
                    String ukuran = model.getValueAt(selectedRow, 5).toString();
                    String gender = model.getValueAt(selectedRow, 6).toString();
                    String warna = model.getValueAt(selectedRow, 7).toString();
                    String harga = model.getValueAt(selectedRow, 8).toString();
                    
                    txtKode.setText(kode);
                    txtNama.setText(nama);
                    txtBrand.setText(brand);
                    
                    cmbKategori.setSelectedItem(kategori);
                    
                    if(footwear.equals("Sandals")) {
                        rbSandal.setSelected(true);
                    }
                    else if(footwear.equals("Sneakers")) {
                        rbSneakers.setSelected(true);
                    }
                    else {
                        rbSportP.setSelected(true);
                    }
                
                    txtUkuran.setText(ukuran);
                    
                    if(gender.equals("Men")) {
                        rbMen.setSelected(true);
                    }
                    else if(gender.equals("Women")) {
                        rbWomen.setSelected(true);
                    }
                    else {
                        rbUnisex.setSelected(true);
                    }   
                    
                    txtWarna.setText(warna);
                    txtHarga.setText(harga);
                    
                    txtKode.setEditable(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFootwear = new javax.swing.ButtonGroup();
        bgGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        cmbKategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rbSandal = new javax.swing.JRadioButton();
        rbSneakers = new javax.swing.JRadioButton();
        rbSportP = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbMen = new javax.swing.JRadioButton();
        rbWomen = new javax.swing.JRadioButton();
        rbUnisex = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtUkuran = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHasil = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pendataan Sepatu Sport");

        jPanel1.setBackground(new java.awt.Color(196, 223, 223));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1228, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(248, 246, 244));

        jLabel1.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel2.setText("Brand");

        jLabel3.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel3.setText("Kategori");

        txtNama.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N

        txtBrand.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N

        btnSubmit.setFont(new java.awt.Font("Yet R", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        cmbKategori.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tennis", "Basketball", "Walking", "Cycling", "Soccer", "Running", "Badminton", "Golf" }));

        jLabel5.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel5.setText("Footwear");

        rbSandal.setBackground(new java.awt.Color(248, 246, 244));
        bgFootwear.add(rbSandal);
        rbSandal.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        rbSandal.setText("Sandals");

        rbSneakers.setBackground(new java.awt.Color(248, 246, 244));
        bgFootwear.add(rbSneakers);
        rbSneakers.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        rbSneakers.setText("Sneakers");

        rbSportP.setBackground(new java.awt.Color(248, 246, 244));
        bgFootwear.add(rbSportP);
        rbSportP.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        rbSportP.setText("Sports Performance");

        jLabel6.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel6.setText("Ukuran");

        jLabel7.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel7.setText("Gender");

        rbMen.setBackground(new java.awt.Color(248, 246, 244));
        bgGender.add(rbMen);
        rbMen.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        rbMen.setText("Men");

        rbWomen.setBackground(new java.awt.Color(248, 246, 244));
        bgGender.add(rbWomen);
        rbWomen.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        rbWomen.setText("Women");

        rbUnisex.setBackground(new java.awt.Color(248, 246, 244));
        bgGender.add(rbUnisex);
        rbUnisex.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        rbUnisex.setText("Unisex");

        jLabel8.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel8.setText("Warna");

        txtWarna.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yet R", 1, 24)); // NOI18N
        jLabel9.setText("PENDATAAN SEPATU SPORT");

        btnClear.setFont(new java.awt.Font("Yet R", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Yet R", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtUkuran.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N

        txtHarga.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel10.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel4.setText("Kode");

        txtKode.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel11.setText("Kolom Pencarian Berdasarkan Ketgori Sepatu");

        jLabel12.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jLabel12.setText("Hasil Pendataan");

        btnUpdate.setFont(new java.awt.Font("Yet R", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Yet R", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tbHasil.setAutoCreateRowSorter(true);
        tbHasil.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        tbHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHasil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbHasil.setGridColor(new java.awt.Color(196, 223, 223));
        tbHasil.setSelectionBackground(new java.awt.Color(196, 223, 223));
        jScrollPane1.setViewportView(tbHasil);

        txtCari.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N

        btnCari.setFont(new java.awt.Font("Yet R", 0, 14)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbSportP)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbMen)
                                .addGap(86, 86, 86)
                                .addComponent(rbWomen)
                                .addGap(80, 80, 80)
                                .addComponent(rbUnisex))
                            .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBrand, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtWarna, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(rbSandal)
                            .addGap(60, 60, 60)
                            .addComponent(rbSneakers))
                        .addComponent(txtUkuran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rbSandal)
                            .addComponent(rbSneakers)
                            .addComponent(rbSportP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rbMen)
                            .addComponent(rbWomen)
                            .addComponent(rbUnisex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        String kode = txtKode.getText();
        String nama = txtNama.getText();
        String brand = txtBrand.getText();
        String kategori = (String) cmbKategori.getSelectedItem();
        
        String footwear = rbSandal.isSelected()? "Sandals" : rbSneakers.isSelected()? "Sneakers" : "Sport Performances";
        
        String ukuran = txtUkuran.getText();
        
        String gender = rbMen.isSelected()? "Men" : rbWomen.isSelected()? "Women" : "Unisex";
        
        String warna = txtWarna.getText();
        String harga = txtHarga.getText();
        
        if (kode.isEmpty() || nama.isEmpty() || brand.isEmpty() || kategori.isEmpty() || bgFootwear.getSelection() == null || ukuran.isEmpty() || bgGender.getSelection() == null || warna.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Lengkapi Data Terlebih Dahulu !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else{
            try {
                try (Connection conn = Config.getConnection()) {
                    Statement stmt = conn.createStatement();
                    String query = "SELECT * FROM datasepatu WHERE kode ='" + kode + "'";
                    ResultSet rs = stmt.executeQuery(query);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Kode Produk telah Terdaftar !", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    } else {
                        // Insert user information into the database
                        query = "INSERT INTO datasepatu (kode, nama, brand, kategori, footwear, ukuran, gender, warna, harga) VALUES "
                                + "('" + kode + "', '" + nama + "', '" + brand + "', '" + kategori + "', '" + footwear + "', "
                                + "'" + ukuran + "', '" + gender + "', '" + warna + "', '" + harga + "')";
                        stmt.executeUpdate(query);
                        JOptionPane.showMessageDialog(this, "Produk Berhasil Ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        clear();
                        tampilData();
                    }
                }
            } catch (HeadlessException | SQLException ex) {
                System.out.println("Produk Gagal Ditambahkan !");
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        Home home = new Home();
        home.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        if(tbHasil.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Klik Data Sepatu Terlebih Dahulu !", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String footwear = null, gender = null;
        
        String kode = txtKode.getText();
        String nama = txtNama.getText();
        String brand = txtBrand.getText();
        String kategori = (String) cmbKategori.getSelectedItem();
        
        footwear = rbSandal.isSelected()? "Sandals" : rbSneakers.isSelected()? "Sneakers" : "Sport Performances";
        
        String ukuran = txtUkuran.getText();
        
        gender = rbMen.isSelected()? "Men" : rbWomen.isSelected()? "Women" : "Unisex";
        
        String warna = txtWarna.getText();
        String harga = txtHarga.getText();
                     
        try {           
            String query = "UPDATE datasepatu SET kode = '" + kode + "', nama = '" + nama + "', brand = '" + brand + "', kategori = '" + kategori + "', "
                        + "footwear = '" + footwear + "', ukuran = '" + ukuran + "', gender = '" + gender + "', warna = '" + warna + "', harga = '" + harga + "'"
                        + "WHERE kode = '" + txtKode.getText() +"'";
            
            Connection conn = Config.getConnection();
            Statement st = conn.createStatement();
            st.execute(query);
            JOptionPane.showMessageDialog(null,"Produk Berhasil Diupdate", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
        } catch (Exception e) {
           System.out.println("Produk Gagal Diupdate !");
        }  
        clear();
        txtKode.setEditable(true);
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        if(tbHasil.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Klik Data Sepatu Terlebih Dahulu !", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {           
            String query = "DELETE FROM datasepatu WHERE kode = '" +txtKode.getText()+"'";
            
            Connection conn = Config.getConnection();
            Statement st = conn.createStatement();
            st.execute(query);
            JOptionPane.showMessageDialog(null,"Produk Berhasil Dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
        } catch (Exception e) {
           System.out.println("Produk Gagal Dihapus !");
        }
        clear();
        txtKode.setEditable(true);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
            
        tampilData();
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPendataan().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFootwear;
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbMen;
    private javax.swing.JRadioButton rbSandal;
    private javax.swing.JRadioButton rbSneakers;
    private javax.swing.JRadioButton rbSportP;
    private javax.swing.JRadioButton rbUnisex;
    private javax.swing.JRadioButton rbWomen;
    private javax.swing.JTable tbHasil;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUkuran;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables

    private void tampilData(){
        int row = tbHasil.getRowCount();
        for (int i=0; i<row; i++){
        model.removeRow(0);}

    try {
            String query = "SELECT * FROM datasepatu";
            Connection conn = Config.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)};
                model.addRow(data);                      
            }
        } catch (Exception e) {            
            System.out.println("Data Gagal Terbaca !");
        }
    }
    
    private void tampilDataCari(){
        int row = tbHasil.getRowCount();
        for (int i=0; i<row; i++){
        model.removeRow(0);}
        
        try {
            if(txtCari.getText() != null){
                String query = "SELECT * FROM datasepatu WHERE kategori like '%" + txtCari.getText() + "%'";
                Connection conn = Config.getConnection();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(query);
                while(rs.next()){
                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)};
                model.addRow(data);                      
                }
            }
            else{
                tampilData();
            }
            
        } catch (Exception e) {            
            System.out.println("Data Gagal Terbaca !");
        }
    }
    
    private void clear(){
        txtKode.setText("");
        txtNama.setText("");
        txtBrand.setText("");
        cmbKategori.setSelectedIndex(-1);
        bgFootwear.clearSelection();
        bgGender.clearSelection();
        txtUkuran.setText("");
        txtWarna.setText("");
        txtHarga.setText("");
    }

    
}
